version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8001:80"
        volumes:
            - ./code:/var/www/
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build:
          args:
            user: sammy
            uid: 1000
          context: .
          dockerfile: Dockerfile
        working_dir: /var/www/
        volumes:
            - ./code/backend:/var/www/backend
        networks:
            - code-network
    frontend:
      container_name: client
      build:
        context: .
        dockerfile: vuejsDockerfile
      volumes:
        - ./code/frontend:/app
      ports:
        - '8002:80'
    db:
        image: mysql:5.7

        ports:
            - "3306:3306"
        environment:
          - "MYSQL_ROOT_PASSWORD=secret"
          - "MYSQL_DATABASE=site_crud_db"
          - "MYSQL_USER=dbuser"
          - "MYSQL_PASSWORD=secret"
        networks:
            - code-network
        volumes:
          - ./mysql_data:/var/lib/mysql
volumes:
  my-datavolume:

networks:
    code-network:
        driver: bridge
